title: Neall Struwig
email: neallstruwig@gmail.com
description: >-
  Portfolio of Neall Struwig, a data specialist with experience in 
  research, analytics, and technology-driven solutions in healthcare 
  and beyond. Showcasing projects, skills, and professional insights.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://NeallS.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  "NeallS"
linkedin_username: "neall-struwig"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation links (use this for easy linking in layouts)
navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Resume"
    url: "/resume"
  - title: "Blog"
    url: "/blog"
  - title: "Contact"
    url: "/contact"

# Social links
social:
  email: "neallstruwig@gmail.com"
  github: "https://github.com/NeallS"
  linkedin: "https://www.linkedin.com/in/neall-struwig/"
