title: "Neall Struwig | Data & Research Specialist"
email: "neallstruwig@gmail.com"
description: >-
  Portfolio of Neall Struwig, a data specialist in research, analytics, and 
  healthcare technology. Showcasing projects, skills, and insights.
baseurl: "" 
url: "https://NeallS.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sidebar (Left Navigation Bar)
sidebar:
  - image: "/assets/profile.jpeg"  # Add a profile picture in assets/
  - title: "Neall Struwig"
  - text: "Data Scientist | Research Specialist"
  - url: "/about/"
  - entries:
      - title: "Projects"
        url: "/projects/"
      - title: "Resume"
        url: "/resume/"
      - title: "Contact"
        url: "/contact/"

# Social Links
social:
  email: "neallstruwig@gmail.com"
  github: "https://github.com/NeallS"
  linkedin: "https://www.linkedin.com/in/neallstruwig/"
