title: "Neall Struwig | Data & Research Specialist"
email: "neallstruwig@gmail.com"
description: >-
  Portfolio of Neall Struwig, a data specialist in research, analytics, and 
  healthcare technology. Showcasing projects, skills, and insights.
baseurl: "" 
url: "https://NeallS.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable Sidebar Layout
minimal_mistakes_skin: "default"
layout: single
author_profile: true

# Remove Top Navigation Bar
header:
  nav: false  # This removes the horizontal navigation bar

# Sidebar Configuration
sidebar:
  nav: "main"  # Uses the navigation defined in _data/navigation.yml
  sticky: true  # Keeps the sidebar visible when scrolling
  collapse: true  # Makes the sidebar collapsible

# Social Links
social:
  email: "neallstruwig@gmail.com"
  github: "https://github.com/NeallS"
  linkedin: "https://www.linkedin.com/in/neallstruwig/"
