title: "Neall Struwig | Data & Research Specialist"
email: "neallstruwig@gmail.com"
description: >-
  Portfolio of Neall Struwig, a data specialist in research, analytics, and 
  healthcare technology. Showcasing projects, skills, and insights.
baseurl: "" 
url: "https://NeallS.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable Default Navigation Bar (Remove Sidebar)
header:
  nav: true  # Keep only the top navigation bar

# Remove Sidebar
sidebar:
  nav: ""  # Disables the left sidebar

# Navigation Menu
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Resume"
    url: "/resume/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Social Links
social:
  email: "neallstruwig@gmail.com"
  github: "https://github.com/NeallS"
  linkedin: "https://www.linkedin.com/in/neallstruwig/"
